version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    volumes:
      - my-db:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shop_db
      MYSQL_USER: fisher_user
      MYSQL_PASSWORD: 25_fisher13
  composer:
    image: composer
    volumes:
      - ./:/app
    working_dir: /app
  node:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: "npm run watch"  # Команда для запуска сборки и слежения за изменениями


  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
volumes:
  my-db:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
